# Generated by Django 5.2.7 on 2025-10-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip_addr",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
