# Generated by Django 5.2.7 on 2025-10-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_address_zip_addr"),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection(title)
            VALUES("collection1")
        """, """
            DELETE FROM store_collection WHERE title="collection1"
        """)
    ]
